#!/usr/bin/env python3
"""Render audio using the same sample-playback strategy as Ableton Learning Music.

This reproduces the mechanism used by the "The playground" page:
1. Drum sounds are one-shot samples loaded through Tone.Players.
2. Tonal sounds are sparse keymaps loaded through Tone.Sampler.
3. Missing pitches are generated by picking the nearest mapped sample and
   changing playback rate by semitone ratio.
4. Tonal voices use instrument-specific release tails.
5. Drum choke rules (for example closed hat cutting open hat) are respected.

The script intentionally stays dependency-free and delegates decoding,
pitch-shifting and mixing to ffmpeg/ffprobe.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple


OUTPUT_SAMPLE_RATE = 48_000
DRUM_FADE_OUT_SECONDS = 0.01
FFMPEG_BIN = "ffmpeg"
FFPROBE_BIN = "ffprobe"


@dataclass(frozen=True)
class SampleDef:
    name: str
    midi: int
    filename: str
    choke: Optional[int] = None


@dataclass(frozen=True)
class BankDef:
    category: str
    kind: str  # "drumkit" or "tonal"
    release: float
    samples: Tuple[SampleDef, ...]


BANK_ALIASES = {
    "drums": "beats",
    "drumkit": "beats",
    "beats": "beats",
    "bass": "basslines",
    "bassline": "basslines",
    "basslines": "basslines",
    "piano": "chords",
    "chords": "chords",
    "synth": "melodies",
    "melody": "melodies",
    "melodies": "melodies",
}


BANKS: Dict[str, BankDef] = {
    "beats": BankDef(
        category="beats",
        kind="drumkit",
        release=DRUM_FADE_OUT_SECONDS,
        samples=(
            SampleDef("Kick", 36, "Kick.ogg"),
            SampleDef("Rim", 37, "Rim.ogg"),
            SampleDef("Snare", 38, "Snare.ogg"),
            SampleDef("Clap", 39, "Clap.ogg"),
            SampleDef("ClosedHat", 42, "ClosedHat.ogg", choke=46),
            SampleDef("OpenHat", 46, "OpenHat.ogg"),
            SampleDef("TomHi", 48, "TomHi.ogg"),
            SampleDef("Ride", 51, "Ride.ogg"),
        ),
    ),
    "basslines": BankDef(
        category="basslines",
        kind="tonal",
        release=0.10,
        samples=(
            SampleDef("boffner1", 24, "boffner1.ogg"),
            SampleDef("boffner2", 36, "boffner2.ogg"),
        ),
    ),
    "chords": BankDef(
        category="chords",
        kind="tonal",
        release=0.40,
        samples=(
            SampleDef("C1v10", 24, "C1v10.ogg"),
            SampleDef("Fs1v10", 30, "Fs1v10.ogg"),
            SampleDef("C2v10", 36, "C2v10.ogg"),
            SampleDef("Fs2v10", 42, "Fs2v10.ogg"),
            SampleDef("C3v10", 48, "C3v10.ogg"),
            SampleDef("Fs3v10", 54, "Fs3v10.ogg"),
            SampleDef("C4v10", 60, "C4v10.ogg"),
            SampleDef("Fs4v10", 66, "Fs4v10.ogg"),
            SampleDef("C5v10", 72, "C5v10.ogg"),
            SampleDef("Fs5v10", 78, "Fs5v10.ogg"),
            SampleDef("C6v10", 84, "C6v10.ogg"),
            SampleDef("Fs6v10", 90, "Fs6v10.ogg"),
            SampleDef("C7v10", 96, "C7v10.ogg"),
            SampleDef("Fs7v10", 102, "Fs7v10.ogg"),
            SampleDef("C8v10", 108, "C8v10.ogg"),
        ),
    ),
    "melodies": BankDef(
        category="melodies",
        kind="tonal",
        release=0.06,
        samples=(
            SampleDef("sinelead1", 48, "sinelead1.ogg"),
            SampleDef("sinelead2", 60, "sinelead2.ogg"),
            SampleDef("sinelead3", 72, "sinelead3.ogg"),
            SampleDef("sinelead4", 84, "sinelead4.ogg"),
        ),
    ),
}


@dataclass
class Voice:
    source_path: Path
    start_seconds: float
    velocity: float
    playback_rate: float = 1.0
    trim_end_seconds: Optional[float] = None
    fade_start_seconds: Optional[float] = None
    fade_duration_seconds: Optional[float] = None
    source_sample_rate: int = OUTPUT_SAMPLE_RATE


@dataclass
class AudioInfo:
    duration_seconds: float
    sample_rate: int


class RendererError(RuntimeError):
    pass


def run_command(args: Sequence[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            list(args),
            check=True,
            text=True,
            capture_output=True,
        )
    except FileNotFoundError as exc:
        raise RendererError(f"Command not found: {args[0]}") from exc
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip() if exc.stderr else ""
        raise RendererError(f"Command failed: {' '.join(args)}\n{stderr}") from exc


def clamp(value: float, min_value: float, max_value: float) -> float:
    return max(min_value, min(max_value, value))


def canonical_bank_name(value: str) -> str:
    key = value.strip().lower()
    if key not in BANK_ALIASES:
        raise RendererError(
            f"Unknown instrument '{value}'. Valid names: {', '.join(sorted(BANK_ALIASES))}"
        )
    return BANK_ALIASES[key]


def note_to_midi(note: str) -> int:
    note = note.strip()
    if not note:
        raise RendererError("Empty note string")
    if len(note) < 2:
        raise RendererError(f"Invalid note '{note}'")

    pitch_class = note[0].upper()
    accidental = ""
    octave_part = note[1:]
    if octave_part and octave_part[0] in ("#", "b", "B"):
        accidental = "#" if octave_part[0] == "#" else "b"
        octave_part = octave_part[1:]

    if not octave_part or not octave_part.lstrip("-").isdigit():
        raise RendererError(f"Invalid note '{note}'")

    pitch_map = {
        "C": 0,
        "D": 2,
        "E": 4,
        "F": 5,
        "G": 7,
        "A": 9,
        "B": 11,
    }
    if pitch_class not in pitch_map:
        raise RendererError(f"Invalid note '{note}'")

    semitone = pitch_map[pitch_class]
    if accidental == "#":
        semitone += 1
    elif accidental == "b":
        semitone -= 1

    octave = int(octave_part)
    return (octave + 1) * 12 + semitone


def frequency_to_midi_float(frequency_hz: float) -> float:
    if frequency_hz <= 0:
        raise RendererError("frequency_hz must be > 0")
    return 69.0 + 12.0 * math.log2(frequency_hz / 440.0)


def beats_to_seconds(beats: float, tempo_bpm: float) -> float:
    return 60.0 * beats / tempo_bpm


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def get_audio_info(path: Path, cache: Dict[Path, AudioInfo]) -> AudioInfo:
    if path in cache:
        return cache[path]

    proc = run_command(
        (
            FFPROBE_BIN,
            "-v",
            "error",
            "-select_streams",
            "a:0",
            "-show_entries",
            "stream=sample_rate:format=duration",
            "-of",
            "json",
            str(path),
        )
    )
    data = json.loads(proc.stdout)
    duration = float(data["format"]["duration"])
    sample_rate = int(data["streams"][0]["sample_rate"])
    info = AudioInfo(duration_seconds=duration, sample_rate=sample_rate)
    cache[path] = info
    return info


def resolve_asset_root(asset_root_arg: Optional[str]) -> Path:
    if asset_root_arg:
        root = Path(asset_root_arg).expanduser().resolve()
    else:
        root = Path.cwd() / "ableton-playground-audio"

    if not root.exists():
        raise RendererError(f"Asset root not found: {root}")
    manifest = root / "manifest.json"
    if not manifest.exists():
        raise RendererError(f"manifest.json not found under asset root: {root}")
    return root


def resolve_sample_path(asset_root: Path, bank: BankDef, sample: SampleDef) -> Path:
    path = asset_root / bank.category / sample.filename
    if not path.exists():
        raise RendererError(f"Missing sample file: {path}")
    return path


def choose_closest_sample(bank: BankDef, midi_rounded: int) -> SampleDef:
    sample_by_midi = {sample.midi: sample for sample in bank.samples}
    max_interval = 96
    for interval in range(max_interval + 1):
        higher = midi_rounded + interval
        if higher in sample_by_midi:
            return sample_by_midi[higher]
        lower = midi_rounded - interval
        if lower in sample_by_midi:
            return sample_by_midi[lower]
    raise RendererError(f"No sample found near MIDI note {midi_rounded}")


def resolve_target_midi_float(event: Dict[str, Any]) -> float:
    if "midi" in event:
        return float(event["midi"])
    if "note" in event:
        return float(note_to_midi(str(event["note"])))
    if "frequency_hz" in event:
        midi_float = frequency_to_midi_float(float(event["frequency_hz"]))
        pitch_mode = str(event.get("pitch_mode", "playground")).strip().lower()
        if pitch_mode == "playground":
            return float(round(midi_float))
        if pitch_mode == "tone_sampler":
            return midi_float
        raise RendererError(
            "pitch_mode must be 'playground' or 'tone_sampler' when frequency_hz is used"
        )
    raise RendererError("Tonal event requires one of: midi, note, frequency_hz")


def event_time_seconds(event: Dict[str, Any], tempo_bpm: float) -> float:
    if "time_seconds" in event:
        return float(event["time_seconds"])
    if "time_beats" in event:
        return beats_to_seconds(float(event["time_beats"]), tempo_bpm)
    raise RendererError("Event requires time_seconds or time_beats")


def event_duration_seconds(event: Dict[str, Any], tempo_bpm: float) -> float:
    if "duration_seconds" in event:
        return float(event["duration_seconds"])
    if "duration_beats" in event:
        return beats_to_seconds(float(event["duration_beats"]), tempo_bpm)
    raise RendererError("Tonal event requires duration_seconds or duration_beats")


def build_tonal_voice(
    bank: BankDef,
    event: Dict[str, Any],
    asset_root: Path,
    tempo_bpm: float,
    audio_cache: Dict[Path, AudioInfo],
) -> Voice:
    midi_float = resolve_target_midi_float(event)
    midi_rounded = round(midi_float)
    remainder = midi_float - midi_rounded
    sample = choose_closest_sample(bank, midi_rounded)
    sample_path = resolve_sample_path(asset_root, bank, sample)
    info = get_audio_info(sample_path, audio_cache)

    semitone_offset = (midi_rounded - sample.midi) + remainder
    playback_rate = 2 ** (semitone_offset / 12.0)
    natural_duration = info.duration_seconds / playback_rate

    note_duration = event_duration_seconds(event, tempo_bpm)
    start_seconds = event_time_seconds(event, tempo_bpm)
    velocity = clamp(float(event.get("velocity", 1.0)), 0.0, 1.0)

    trim_end_seconds: Optional[float] = natural_duration
    fade_start_seconds: Optional[float] = None
    fade_duration_seconds: Optional[float] = None

    if note_duration < natural_duration:
        fade_start_seconds = note_duration
        fade_duration_seconds = bank.release
        trim_end_seconds = min(natural_duration, note_duration + bank.release)

    return Voice(
        source_path=sample_path,
        start_seconds=start_seconds,
        velocity=velocity,
        playback_rate=playback_rate,
        trim_end_seconds=trim_end_seconds,
        fade_start_seconds=fade_start_seconds,
        fade_duration_seconds=fade_duration_seconds,
        source_sample_rate=info.sample_rate,
    )


def build_drum_voices(
    bank: BankDef,
    events: Sequence[Dict[str, Any]],
    asset_root: Path,
    tempo_bpm: float,
    audio_cache: Dict[Path, AudioInfo],
) -> List[Voice]:
    sample_by_midi = {sample.midi: sample for sample in bank.samples}
    normalized: List[Dict[str, Any]] = []
    for original in events:
        if "midi" not in original:
            raise RendererError("Drum event requires midi")
        midi = int(original["midi"])
        if midi not in sample_by_midi:
            raise RendererError(f"Unsupported drum midi {midi} for bank '{bank.category}'")
        normalized.append(
            {
                "midi": midi,
                "time_seconds": event_time_seconds(original, tempo_bpm),
                "velocity": clamp(float(original.get("velocity", 1.0)), 0.0, 1.0),
                "choke": sample_by_midi[midi].choke,
            }
        )

    normalized.sort(key=lambda item: (item["time_seconds"], item["midi"]))

    groups: List[List[Dict[str, Any]]] = []
    for event in normalized:
        if not groups:
            groups.append([event])
            continue
        last_time = groups[-1][0]["time_seconds"]
        if abs(last_time - event["time_seconds"]) < 1e-9:
            groups[-1].append(event)
        else:
            groups.append([event])

    started_voices: List[Dict[str, Any]] = []
    active = []
    for group in groups:
        choked_midis = {event["choke"] for event in group if event.get("choke") is not None}

        for event in group:
            choke_target = event.get("choke")
            if choke_target is None:
                continue
            for active_voice in active:
                if active_voice["midi"] == choke_target and active_voice["end_seconds"] > event["time_seconds"]:
                    active_voice["end_seconds"] = event["time_seconds"]
                    active_voice["fade_start_seconds"] = max(
                        0.0, event["time_seconds"] - active_voice["start_seconds"]
                    )
                    active_voice["fade_duration_seconds"] = bank.release

        for event in group:
            if event["midi"] in choked_midis:
                continue

            sample = sample_by_midi[event["midi"]]
            sample_path = resolve_sample_path(asset_root, bank, sample)
            info = get_audio_info(sample_path, audio_cache)
            voice = {
                "midi": event["midi"],
                "start_seconds": event["time_seconds"],
                "end_seconds": event["time_seconds"] + info.duration_seconds,
                "fade_start_seconds": None,
                "fade_duration_seconds": None,
                "source_path": sample_path,
                "velocity": event["velocity"],
                "source_sample_rate": info.sample_rate,
            }
            active.append(voice)
            started_voices.append(voice)

        current_time = group[0]["time_seconds"]
        active = [voice for voice in active if voice["end_seconds"] > current_time]

    rendered: List[Voice] = []
    for voice in started_voices:
        relative_end = voice["end_seconds"] - voice["start_seconds"]
        if relative_end <= 0:
            continue
        rendered.append(
            Voice(
                source_path=voice["source_path"],
                start_seconds=voice["start_seconds"],
                velocity=voice["velocity"],
                playback_rate=1.0,
                trim_end_seconds=relative_end,
                fade_start_seconds=voice["fade_start_seconds"],
                fade_duration_seconds=voice["fade_duration_seconds"],
                source_sample_rate=voice["source_sample_rate"],
            )
        )
    return rendered


def create_voices_from_sequence(
    sequence_data: Dict[str, Any],
    asset_root: Path,
) -> List[Voice]:
    tempo_bpm = float(sequence_data.get("tempo", 85.0))
    tracks = sequence_data.get("tracks")
    if not isinstance(tracks, list) or not tracks:
        raise RendererError("Sequence JSON must contain a non-empty 'tracks' array")

    audio_cache: Dict[Path, AudioInfo] = {}
    voices: List[Voice] = []

    for track in tracks:
        bank_name = canonical_bank_name(str(track["instrument"]))
        bank = BANKS[bank_name]
        events = track.get("events")
        if not isinstance(events, list) or not events:
            continue
        if bank.kind == "drumkit":
            voices.extend(build_drum_voices(bank, events, asset_root, tempo_bpm, audio_cache))
        else:
            for event in events:
                voices.append(build_tonal_voice(bank, event, asset_root, tempo_bpm, audio_cache))

    return voices


def build_filter_chain(voice: Voice, label: str) -> str:
    parts = [
        f"aformat=sample_rates={voice.source_sample_rate}:sample_fmts=fltp",
    ]

    if abs(voice.playback_rate - 1.0) > 1e-9:
        parts.append(f"asetrate={voice.source_sample_rate}*{voice.playback_rate:.12f}")
        parts.append(f"aresample={OUTPUT_SAMPLE_RATE}")
    else:
        parts.append(f"aresample={OUTPUT_SAMPLE_RATE}")

    if voice.trim_end_seconds is not None:
        parts.append(f"atrim=0:{voice.trim_end_seconds:.6f}")

    if (
        voice.fade_start_seconds is not None
        and voice.fade_duration_seconds is not None
        and voice.fade_duration_seconds > 0
        and voice.fade_start_seconds < (voice.trim_end_seconds or float("inf"))
    ):
        parts.append(
            f"afade=t=out:st={voice.fade_start_seconds:.6f}:d={voice.fade_duration_seconds:.6f}"
        )

    parts.append(f"volume={voice.velocity:.6f}")

    delay_ms = max(0, int(round(voice.start_seconds * 1000)))
    parts.append(f"adelay={delay_ms}|{delay_ms}")

    return ",".join(parts) + label


def render_voices(voices: Sequence[Voice], output_path: Path) -> None:
    if not voices:
        raise RendererError("No voices to render")

    ffmpeg_inputs: List[str] = []
    filter_parts: List[str] = []
    mix_labels: List[str] = []

    for index, voice in enumerate(voices):
        ffmpeg_inputs.extend(["-i", str(voice.source_path)])
        out_label = f"[v{index}]"
        filter_parts.append(f"[{index}:a]{build_filter_chain(voice, out_label)}")
        mix_labels.append(out_label)

    filter_parts.append(
        "".join(mix_labels)
        + f"amix=inputs={len(mix_labels)}:dropout_transition=0:normalize=0,alimiter=limit=0.97[out]"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    command = [
        FFMPEG_BIN,
        "-y",
        *ffmpeg_inputs,
        "-filter_complex",
        ";".join(filter_parts),
        "-map",
        "[out]",
        str(output_path),
    ]
    run_command(command)


def parse_sequence_file(sequence_path: Path) -> Dict[str, Any]:
    if not sequence_path.exists():
        raise RendererError(f"Sequence file not found: {sequence_path}")
    return load_json(sequence_path)


def render_note_command(args: argparse.Namespace) -> None:
    instrument = canonical_bank_name(args.instrument)
    bank = BANKS[instrument]
    asset_root = resolve_asset_root(args.asset_root)

    event: Dict[str, Any] = {
        "time_seconds": 0,
        "velocity": args.velocity,
    }
    if bank.kind == "drumkit":
        event["midi"] = int(args.midi if args.midi is not None else note_to_midi(args.note))
    else:
        if args.frequency_hz is not None:
            event["frequency_hz"] = args.frequency_hz
            event["pitch_mode"] = args.pitch_mode
        elif args.midi is not None:
            event["midi"] = args.midi
        elif args.note is not None:
            event["note"] = args.note
        else:
            raise RendererError("render-note requires --note, --midi or --frequency-hz")

        if args.duration_seconds is not None:
            event["duration_seconds"] = args.duration_seconds
        else:
            event["duration_beats"] = args.duration_beats

    if bank.kind == "drumkit":
        sequence = {"tempo": args.tempo, "tracks": [{"instrument": instrument, "events": [event]}]}
    else:
        sequence = {"tempo": args.tempo, "tracks": [{"instrument": instrument, "events": [event]}]}

    voices = create_voices_from_sequence(sequence, asset_root)
    render_voices(voices, Path(args.output).resolve())


def render_sequence_command(args: argparse.Namespace) -> None:
    asset_root = resolve_asset_root(args.asset_root)
    sequence = parse_sequence_file(Path(args.sequence).resolve())
    voices = create_voices_from_sequence(sequence, asset_root)
    render_voices(voices, Path(args.output).resolve())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render audio using Ableton Learning Music playground sample logic."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    sequence_parser = subparsers.add_parser("render-sequence", help="Render a sequence JSON file")
    sequence_parser.add_argument("--sequence", required=True, help="Path to sequence JSON")
    sequence_parser.add_argument("--output", required=True, help="Output audio path")
    sequence_parser.add_argument(
        "--asset-root",
        help="Directory containing manifest.json and the beats/basslines/chords/melodies folders",
    )
    sequence_parser.set_defaults(func=render_sequence_command)

    note_parser = subparsers.add_parser("render-note", help="Render one note or drum hit")
    note_parser.add_argument("--instrument", required=True, help="beats/basslines/chords/melodies")
    note_parser.add_argument("--output", required=True, help="Output audio path")
    note_parser.add_argument("--tempo", type=float, default=85.0, help="Tempo in BPM")
    note_parser.add_argument("--velocity", type=float, default=1.0, help="0.0 to 1.0")
    note_parser.add_argument("--note", help="Note name such as C4 or F#2")
    note_parser.add_argument("--midi", type=float, help="MIDI note number")
    note_parser.add_argument("--frequency-hz", type=float, help="Target frequency in Hz")
    note_parser.add_argument(
        "--pitch-mode",
        default="playground",
        choices=("playground", "tone_sampler"),
        help="How frequency_hz is converted to pitch",
    )
    note_parser.add_argument("--duration-beats", type=float, default=1.0, help="Held note length")
    note_parser.add_argument("--duration-seconds", type=float, help="Held note length in seconds")
    note_parser.add_argument(
        "--asset-root",
        help="Directory containing manifest.json and the beats/basslines/chords/melodies folders",
    )
    note_parser.set_defaults(func=render_note_command)

    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    if shutil.which(FFMPEG_BIN) is None or shutil.which(FFPROBE_BIN) is None:
        print("ffmpeg and ffprobe are required in PATH", file=sys.stderr)
        return 1

    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
        return 0
    except RendererError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
